bugfix: Fix `table index is nil` error when Spotlight app results don't have a kMDItemDisplayName. Local-ify accidental globals.
ERROR:   LuaSkin: hs.spotlight: .../Seal.spoon//seal_apps.lua:40: table index is nil
stack traceback:
	.../Seal.spoon//seal_apps.lua:40: in upvalue 'modifyNameMap'